=== tramanh9999/netbean/DOM/web/dtddemo/entity/1/combine.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT document (title+, subjectId, subjectName, prerequisite,classes, assessment,syllabus,textbook, textbooks)>

<!ELEMENT title (#PCDATA) >

<!ELEMENT subjectId (#PCDATA)>

<!ELEMENT subjectName (#PCDATA)>

<!ELEMENT prerequisite (subjectId, subjectName)>

<!ELEMENT classes (#PCDATA)>
<!ELEMENT assessment ANY >
<!ATTLIST assessment assessment_type (exam| assignment) #IMPLIED>
<!ELEMENT syllabus (#PCDATA)>

<!ELEMENT textbook (author,booktitle)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT booktitle (#PCDATA)>

<!ELEMENT textbooks (author,booktitle)>

=== tramanh9999/netbean/DOM/build/web/dtddemo/enity/combine.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE document SYSTEM "combine.dtd"[
<!ATTLIST assessment assessment_type (prac|exam) "prac">
<!ELEMENT result (#PCDATA)>
]>


<document>


    <title>Core XML</title>
    <title>With java XML</title>
    <subjectId>495</subjectId>
    <subjectName>XML</subjectName>
    <prerequisite>
        <subjectId>565</subjectId>
        <subjectName>Java</subjectName>
    </prerequisite>
    <classes>435, 456</classes>
    <assessment assessment_type="exam">Online
        <result>7</result>
    </assessment>
    <syllabus>5/9/2011</syllabus>
    <textbook>
        <author>ABV</author>
        <booktitle>Core XML</booktitle>
        
    </textbook>
    
    <textbooks>
        <author>CDF</author>
        <booktitle>With java XML</booktitle>
    </textbooks>
</document>
