=== tramanh9999/netbean/DOM/build/web/dtddemo/entity/1_1_1/combine.dtd
<?xml version="1.0" encoding="UTF-8"?>



<!ENTITY % common.attributes 


'id    ID    #IMPLIED  
account   CDATA   #REQUIRED'
>

<!ELEMENT purchaseOrder (item+, manufacturer, purchaser, purchaserInfo)>


<!ATTLIST purchaseOrder %common.attributes;>
<!ELEMENT item (price, quantity)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

<!ATTLIST item %common.attributes; >

<!ELEMENT manufacturer (#PCDATA) >
<!ATTLIST manufacturer  %common.attributes; >


<!ELEMENT purchaser (#PCDATA) >
<!ATTLIST purchaser  %common.attributes;>



<!ELEMENT purchaserInfo (cash|check|creditcard) >
<!ELEMENT check (#PCDATA) >
<!ELEMENT creditcard EMPTY >
<!ELEMENT cash ANY >

=== tramanh9999/netbean/DOM/build/web/dtddemo/entity/1_1_1/combine.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE purchaseOrder SYSTEM "combine.dtd">
<purchaseOrder id="D001" account="KhanhKT">
    <item id="I001" account="KhanhKT">
        <price>45</price>
        <quantity>23</quantity>
        
    </item>
    
     <item account="KhanhKT">
        <price>2</price>
        <quantity>2213</quantity>
        
    </item>
    
    <manufacturer account="M0012">Academic</manufacturer>
    <purchaser id="P001" account="Khanh">Ltd.</purchaser>
    <purchaserInfo>
        <cash>34123</cash>
    </purchaserInfo>
</purchaseOrder>
