=== tramanh9999/netbean/DOM/build/web/dtddemo/combining/dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT contacts (contact)>
<!ELEMENT contact (name, location, phone, knows, description)>
<!ELEMENT name (firstname, middlename, lastname)>
<!ELEMENT firstname (#PCDATA)> 
<!ELEMENT middlename (#PCDATA)> 
<!ELEMENT lastname (#PCDATA)> 

<!ELEMENT location (adresss|(latitude, longitude))>
<!ELEMENT latitude (#PCDATA)> 
<!ELEMENT longitude (#PCDATA)> 
<!ELEMENT address (#PCDATA)>  


<!ELEMENT phone (#PCDATA)>
<!ELEMENT knows ( #PCDATA)>
<!ELEMENT description (#PCDATA|em|br|strong)*>
<!ELEMENT em (#PCDATA)> 
<!ELEMENT br EMPTY> 
<!ELEMENT strong (#PCDATA)>

=== tramanh9999/netbean/DOM/web/dtddemo/combining/sequence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE contacts  SYSTEM  "dtd.dtd" >
<contacts>
    <contact>
        <name>
            <firstname>Josherp</firstname>
            <middlename>John</middlename>
            <lastname>Fawcest</lastname>
        </name>
        <location>
            <latitude>12312312.123123123</latitude>
            <longitude>321123.1231233</longitude>
        </location>
        
        <phone></phone>
        <knows></knows>
        <description>
            Jotaro is  a developer and author of the Begining XML
            <em>5 edition</em>
            <br/>
            Jooshua
            <strong>loves</strong> XML!
        </description>
    </contact>
</contacts>
